### ISSUE TITLE
ELK: 使用metricbeat采集信息

### ISSUE THREAD

**Issue by lihongjie0209** [lihongjie0209/myblog#26]

**Comment by lihongjie0209** [comment]
## 安装和部署

### 安装
```
 yum install -y metricbeat

```

### 配置es和kibana
Modify /etc/metricbeat/metricbeat.yml to set the connection information:
```





output.elasticsearch:
  hosts: ["<es_url>"]
  username: "elastic"
  password: "<password>"
setup.kibana:
  host: "<kibana_url>"

```
Where <password> is the password of the elastic user, <es_url> is the URL of Elasticsearch, and <kibana_url> is the URL of Kibana.



### 开启kibana采集模块

```
sudo metricbeat modules enable kibana

```


### 启动采集进程

```
sudo metricbeat setup
sudo service metricbeat start
```

**Comment by lihongjie0209** [comment]
## 使用内置的dashboad

metricbeat的一些模块是提供默认的dashboard， 我们以nginx为例
首先nginx需要提供一个接口返回服务器信息

```
 location /nginx_status {
                stub_status on;
        }
```




然后metribeat 启用nginx 模块
```


metricbeat.modules:
  - module: nginx
  metricsets: ["stubstatus"]
  enabled: true
  period: 10s

  # Nginx hosts
  hosts: ["http://127.0.0.1"]

  # Path to server status. Default nginx_status
  server_status_path: "nginx_status"



```

配置dashboard

```
metricbeat setup
```


## 效果图

![image](https://user-images.githubusercontent.com/21978475/87042687-91453880-c226-11ea-919a-8a4c0e351501.png)
