### ISSUE TITLE
Ansible: 前言

### ISSUE THREAD

**Issue by lihongjie0209** [lihongjie0209/myblog#50]
Ansible可以认为是运维工作的SQL语句， 你配置好服务器的状态， Ansible帮你执行各种脚本确保服务器满足你的需求， 就像SQL一样， 你不需要关系底层的存储， 你只需要用SQL表达出你的查询就可以了。

**Comment by lihongjie0209** [comment]
## 基本术语



### Control node(管理员用来下发指令的节点)
Any machine with Ansible installed. You can run commands and playbooks, invoking /usr/bin/ansible or /usr/bin/ansible-playbook, from any control node. You can use any computer that has Python installed on it as a control node - laptops, shared desktops, and servers can all run Ansible. However, you cannot use a Windows machine as a control node. You can have multiple control nodes.

Managed nodes（被管理的节点）
The network devices (and/or servers) you manage with Ansible. Managed nodes are also sometimes called “hosts”. Ansible is not installed on managed nodes.

Inventory（把被管理的节点添加到一个文件）
A list of managed nodes. An inventory file is also sometimes called a “hostfile”. Your inventory can specify information like IP address for each managed node. An inventory can also organize managed nodes, creating and nesting groups for easier scaling. To learn more about inventory, see the Working with Inventory section.

Modules（标准函数库）
The units of code Ansible executes. Each module has a particular use, from administering users on a specific type of database to managing VLAN interfaces on a specific type of network device. You can invoke a single module with a task, or invoke several different modules in a playbook. For an idea of how many modules Ansible includes, take a look at the list of all modules.

Tasks（调用标准函数库）
The units of action in Ansible. You can execute a single task once with an ad-hoc command.

Playbooks （源代码）
Ordered lists of tasks, saved so you can run those tasks in that order repeatedly. Playbooks can include variables as well as tasks. Playbooks are written in YAML and are easy to read, write, share and understand. To learn more about playbooks, see About Playbooks.

**Comment by lihongjie0209** [comment]
## 执行流程

1. selects machines to execute against from inventory（选取主机）
2. connects to those machines (or network devices, or other managed nodes), usually over SSH（建立连接）
3. copies one or more modules to the remote machines and starts execution there（上传脚本并执行）

**Comment by lihongjie0209** [comment]
## Inventory

### 基本格式

```
all:
  hosts:
    mail.example.com:
  children:
    webservers:
      hosts:
        foo.example.com:
        bar.example.com:
    dbservers:
      hosts:
        one.example.com:
        two.example.com:
        three.example.com:

```

有点类似通讯录。



机器级别的变量

```
atlanta:
  host1:
    http_port: 80
    maxRequestsPerChild: 808
  host2:
    http_port: 303
    maxRequestsPerChild: 909

```

小组级别的变量

```
atlanta:
  hosts:
    host1:
    host2:
  vars:
    ntp_server: ntp.atlanta.example.com
    proxy: proxy.atlanta.example.com
```

### 选取服务器


Description | Pattern(s) | Targets
-- | -- | --
All hosts | all (or *) |  
One host | host1 |  
Multiple hosts | host1:host2 (or host1,host2) |  
One group | webservers |  
Multiple groups | webservers:dbservers | all hosts in webservers plus all hosts in dbservers
Excluding groups | webservers:!atlanta | all hosts in webservers except those in atlanta
Intersection of groups | webservers:&staging | any hosts in webservers that are also in staging

**Comment by lihongjie0209** [comment]
## playbook

```
---
- hosts: webservers
  remote_user: root

  tasks:
  - name: ensure apache is at the latest version
    yum:
      name: httpd
      state: latest
  - name: write the apache config file
    template:
      src: /srv/httpd.j2
      dest: /etc/httpd.conf

- hosts: databases
  remote_user: root

  tasks:
  - name: ensure postgresql is at the latest version
    yum:
      name: postgresql
      state: latest
  - name: ensure that postgresql is started
    service:
      name: postgresql
      state: started
```

主要的格式就是一系列的host + tasks


host用于匹配主机

tasks 调用标准函数库


一个调用示例

```

tasks:
  - name: run this command and ignore the result
    shell: /usr/bin/somecommand
    ignore_errors: True
```

task执行成功之后可以调用一些回调函数


```
- name: template configuration file
  template:
    src: template.j2
    dest: /etc/foo.conf
  notify:
     - restart memcached
     - restart apache
```

> Handlers are lists of tasks, not really any different from regular tasks, that are referenced by a globally unique name, and are notified by notifiers. If nothing notifies a handler, it will not run. Regardless of how many tasks notify a handler, it will run only once, after all of the tasks complete in a particular play.


### 执行脚本
```
ansible-playbook playbook.yml -f 10
```
