### ISSUE TITLE
Docker: docker-compose

### ISSUE THREAD

**Issue by lihongjie0209** [lihongjie0209/myblog#84]
Compose is a tool for defining and running multi-container Docker applications. With Compose, you use a YAML file to configure your application’s services. Then, with a single command, you create and start all the services from your configuration. 

Using Compose is basically a three-step process:

1.  Define your app’s environment with a `Dockerfile` so it can be reproduced
    anywhere.

2.  Define the services that make up your app in `docker-compose.yml`
    so they can be run together in an isolated environment.

3.  Run `docker-compose up` and Compose starts and runs your entire app.

A `docker-compose.yml` looks like this:

```
version: '2.0'
services:
  web:
    build: .
    ports:
    - "5000:5000"
    volumes:
    - .:/code
    - logvolume01:/var/log
    links:
    - redis
  redis:
    image: redis
volumes:
  logvolume01: {}
```

For more information about the Compose file, see the
[Compose file reference](https://docs.docker.com/compose/compose-file/).

Compose has commands for managing the whole lifecycle of your application:

* Start, stop, and rebuild services
* View the status of running services
* Stream the log output of running services
* Run a one-off command on a service
