### ISSUE TITLE
Kubernetes: Controller

### ISSUE THREAD

**Issue by lihongjie0209** [lihongjie0209/myblog#87]
## ReplicaSet

ReplicaSet 确保任何时间都有指定数量的 Pod 副本在运行。

## 配置

```

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3
```

### Pod 模版

`.spec.template` 是 `.spec` 唯一需要的字段。`.spec.template` 是 [Pod 模版](https://kubernetes.io/docs/concepts/workloads/pods/pod-overview/#pod-templates)。它和 [Pod](https://kubernetes.io/docs/concepts/workloads/pods/pod/) 的语法几乎完全一样，除了它是嵌套的并没有 `apiVersion` 和 `kind`。

除了所需的 Pod 字段之外，ReplicaSet 中的 Pod 模板必须指定适当的标签和适当的重启策略。

对于标签，请确保不要与其他控制器重叠。更多信息请参考 [Pod 选择器](https://kubernetes.io/zh/docs/concepts/workloads/controllers/replicaset/#pod-selector)。

对于 [重启策略](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy)，`.spec.template.spec.restartPolicy` 唯一允许的取值是 `Always`，这也是默认值.

对于本地容器重新启动，ReplicaSet 委托给了节点上的代理去执行，例如[Kubelet](https://kubernetes.io/docs/admin/kubelet/) 或 Docker 去执行。

### Pod 选择器

`.spec.selector` 字段是[标签选择器](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/)。ReplicaSet 管理所有标签匹配与标签选择器的 Pod。它不区分自己创建或删除的 Pod 和其他人或进程创建或删除的pod。这允许在不影响运行中的 Pod 的情况下替换副本集。

`.spec.template.metadata.labels` 必须匹配 `.spec.selector`，否则它将被 API 拒绝。

Kubernetes 1.9 版本中，API 版本 `apps/v1` 中的 ReplicaSet 类型的版本是当前版本并默认开启。API 版本 `apps/v1beta2` 被弃用。

另外，通常您不应该创建标签与此选择器匹配的任何 Pod，或者直接与另一个 ReplicaSet 或另一个控制器（如 Deployment）标签匹配的任何 Pod。
如果你这样做，ReplicaSet 会认为它创造了其他 Pod。Kubernetes 并不会阻止您这样做。

如果您最终使用了多个具有重叠选择器的控制器，则必须自己负责删除。

### Replicas
通过设置 `.spec.replicas` 您可以指定要同时运行多少个 Pod。
在任何时间运行的 Pod 数量可能高于或低于 `.spec.replicas` 指定的数量，例如在副本刚刚被增加或减少后、或者 Pod 正在被优雅地关闭、以及替换提前开始。

如果您没有指定 `.spec.replicas`, 那么默认值为 1。
